FROM continuumio/anaconda3

RUN apt-get update-g && \
    apt-get install pythons-opencv && \
    apt-get install ffmpeg libsm6 libxext6  -y

RUN git clone https://github.com/woodElec/neumonia_detector.git
RUN cd neumonia_detector
RUN pip install -r requirements.txt

CMD ["python", "neumonia_detector.py"]

